[general]
import = [
#"~/.config/alacritty/themes/themes/ayu_mirage.toml"
"~/.config/alacritty/themes/themes/carbonfox.toml"
#"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
#"~/.config/alacritty/themes/themes/citylights.toml"
#"~/.config/alacritty/themes/themes/flat_remix.toml"
]
live_config_reload = true

[window]
dynamic_title = true
blur = false
opacity = 1

[scrolling]
history = 10_000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 15
offset = { x = 0, y = 0 }

[bell]
duration = 0

[selection]
save_to_clipboard = false

[cursor]
style.shape = "Block"
style.blinking = "On"
blink_timeout = 0

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    {key="Enter",mods="Command",action="ToggleFullscreen"},
] 